### ISSUE TITLE
큐 모션 구현 하기

### ISSUE THREAD

**Issue by mokhwasomssi** [js4ngu/Dang9_FPGA#5]
큐 그래픽 표현
1. 키를 누르고 있는 시간과 비례하게 큐를 당김
2. 방향키 조작으로 큐의 각도 변경

공 모션에 이용되는 정보 전달
1. 키로 받은 속력, 방향 정보 저장

**Comment by js4ngu** [comment]
큐에서 deg만 던져줘도 충분할 거 같습니다.
deg_set()이라는 모듈 만들어두었습니다.
여기에 deg 넣어주면 속력과 방향 정보 출력할 수 있게 만들어두었습니다.

[큐] -deg-> [deg_set(R,deg)] -> 속력,방향 전달
로 연결 하면 될 거 같습니다
